In [17]:
import joblib
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [18]:
model_DT = joblib.load('../models/Typhoid_DT.pkl')
model_GB = joblib.load('../models/Typhoid_GB.pkl')
model_KNN = joblib.load('../models/Typhoid_KNN.pkl')
model_LR = joblib.load('../models/Typhoid_LR.pkl')
model_RFC = joblib.load('../models/Typhoid_RF.pkl')
model_SVM = joblib.load('../models/Typhoid_SVM.pkl')

In [19]:
input_arr = np.array([30,1,1,101,100,60,88,0,1]).reshape(1, -1)

In [20]:
def predict(input, model):
    return model.predict(input)

def predict_proba(input, model):
    return model.predict_proba(input)

In [21]:
res_DT = predict(input_arr, model_DT)
print(res_DT)

res_DT_proba = predict_proba(input_arr, model_DT)
print(res_DT_proba)

[1]
[[0.3 0.7]]


In [22]:
res_GB = predict(input_arr, model_GB)
print(res_GB)

res_GB_proba = predict_proba(input_arr, model_GB)
print(res_GB_proba)

[1]
[[1.33735521e-05 9.99986626e-01]]


In [23]:
res_LR = predict(input_arr, model_LR)
print(res_LR)

res_LR_proba = predict_proba(input_arr, model_LR)
print(res_LR_proba)

[1]
[[0.1253521 0.8746479]]


In [24]:
res_RFC = predict(input_arr, model_RFC)
print(res_RFC)

res_RFC_proba = predict_proba(input_arr, model_RFC)
print(res_RFC_proba)

[1]
[[0.3 0.7]]


In [25]:
res_SVM = predict(input_arr, model_SVM)
print(res_SVM)

#res_SVM_proba = predict_proba(input_arr, model_SVM)
#print(res_SVM_proba)

[1]


In [26]:
ensemble_result = [res_DT_proba[0], res_GB_proba[0], res_LR_proba[0], res_RFC_proba[0]]
print(ensemble_result)

[array([0.3, 0.7]), array([1.33735521e-05, 9.99986626e-01]), array([0.1253521, 0.8746479]), array([0.3, 0.7])]


In [27]:
output = np.mean(ensemble_result, axis = 0)
print(output)

print('Final Prediction - Class {}'.format(output.argmax()))

[0.18134137 0.81865863]
Final Prediction - Class 1
